# Generated by Django 5.0.4 on 2024-05-12 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BahasaPemograman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bahasa', models.CharField(max_length=200)),
                ('tahun_rilis', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sintaks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sintaks', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Variabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_variabel', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_program', models.CharField(max_length=200)),
                ('bahasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.bahasapemograman')),
                ('sintaks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.sintaks')),
                ('variabel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.variabel')),
            ],
        ),
    ]
